# Generated by Django 5.1.6 on 2025-02-18 15:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unavailability',
            name='name',
        ),
        migrations.RemoveField(
            model_name='unavailability',
            name='time',
        ),
        migrations.AddField(
            model_name='unavailability',
            name='end_time',
            field=models.TimeField(default=datetime.time(9, 0)),
        ),
        migrations.AddField(
            model_name='unavailability',
            name='start_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
