# Generated by Django 5.1.6 on 2025-02-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_remove_unavailability_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
