# Generated by Django 5.1.13 on 2025-11-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0002_group_groupunavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailability',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
