# Generated by Django 5.1.13 on 2025-11-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0003_unavailability_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupunavailability',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
