# Generated by Django 5.1.13 on 2025-11-02
# Data migration to convert NULL description values to empty strings

from django.db import migrations


def convert_null_to_empty(apps, schema_editor):
    """Convert NULL description values to empty strings."""
    Unavailability = apps.get_model('calendar_app', 'Unavailability')
    GroupUnavailability = apps.get_model('calendar_app', 'GroupUnavailability')

    # Update Unavailability model
    Unavailability.objects.filter(description__isnull=True).update(description='')

    # Update GroupUnavailability model
    GroupUnavailability.objects.filter(description__isnull=True).update(description='')


def reverse_empty_to_null(apps, schema_editor):
    """Reverse migration: convert empty strings back to NULL."""
    Unavailability = apps.get_model('calendar_app', 'Unavailability')
    GroupUnavailability = apps.get_model('calendar_app', 'GroupUnavailability')

    # Revert Unavailability model
    Unavailability.objects.filter(description='').update(description=None)

    # Revert GroupUnavailability model
    GroupUnavailability.objects.filter(description='').update(description=None)


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0004_alter_groupunavailability_description_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_null_to_empty, reverse_empty_to_null),
    ]
