# Generated by Django 5.1.13 on 2025-11-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0005_convert_description_null_to_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupunavailability',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='unavailability',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
