# Generated by Django 5.1.14 on 2025-11-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_app', '0006_remove_description_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='join_code',
            field=models.CharField(blank=True, help_text='8-character code for joining this group', max_length=8, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='join_code_enabled',
            field=models.BooleanField(default=True, help_text='Whether the join code is currently active'),
        ),
    ]
