# Generated by Django 5.2.8 on 2025-11-24 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0007_group_join_code_group_join_code_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="unavailability",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="unavailability",
            name="parent_recurring_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recurring_instances",
                to="calendar_app.unavailability",
            ),
        ),
        migrations.AddField(
            model_name="unavailability",
            name="recurrence_pattern",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
