# Generated by Django 5.2.8 on 2025-11-24 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("calendar_app", "0008_unavailability_is_recurring_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("meeting_datetime", models.DateTimeField()),
                (
                    "duration_minutes",
                    models.IntegerField(
                        choices=[(30, "30 minutes"), (60, "1 hour"), (120, "2 hours")],
                        default=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("scheduled", "Scheduled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_proposals",
                        to="calendar_app.group",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposed_meetings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MeetingResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "response",
                    models.CharField(
                        choices=[("accept", "Accept"), ("decline", "Decline")],
                        max_length=10,
                    ),
                ),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proposal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="calendar_app.meetingproposal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-responded_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingproposal",
            index=models.Index(
                fields=["group", "status"], name="calendar_ap_group_i_874941_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingproposal",
            index=models.Index(
                fields=["proposed_by", "status"], name="calendar_ap_propose_45ae64_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingproposal",
            index=models.Index(
                fields=["meeting_datetime"], name="calendar_ap_meeting_633038_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingresponse",
            index=models.Index(
                fields=["proposal", "response"], name="calendar_ap_proposa_27ab19_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingresponse",
            index=models.Index(
                fields=["user", "responded_at"], name="calendar_ap_user_id_0271a7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="meetingresponse",
            unique_together={("proposal", "user")},
        ),
    ]
